[package]
name = "starlark-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allocative = "0.3.0"
anyhow = "1.0.75"
serde_json = {version = "1.0.107"}
starlark = "0.10.0"
