[package]
name = "composer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
starlark = "0.10.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.107"
allocative = "0.3.0"
thiserror = "1.0.50"
convert_case = "0.6.0"
