[package]
name = "object-injection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starlark = "0.9.0"
allocative = "0.3.0"
anyhow = "1.0.75"